parkings/models.py
# -*- coding: utf-8 -*-
from werkzeug.security import generate_password_hash, check_password_hash
from flask import current_app

from application import db
from common.models import BaseDocument
from mongoengine import CASCADE


class Parking(BaseDocument):
    display_name = db.StringField(
        verbose_name=u'Parking Title',
        max_length=100
    )

    address = db.StringField(
        verbose_name=u'Address',
        max_length=100,
        required=True,
        unique=True
    )

    is_active = db.BooleanField(
        verbose_name=u'Is Active',
        default=True
    )

    meta = {}

    def __unicode__(self):
        return self.display_name


class ParkingSlot(BaseDocument):
    parking_id = db.ReferenceField('Parking', reverse_delete_rule=CASCADE)
    display_name = db.StringField(
        verbose_name=u'Parking Title',
        max_length=100
    )

    meta = {'collection': 'parkingslot'}

    def __unicode__(self):
        return self.display_name


class Booking(BaseDocument):
    user_id = db.ReferenceField('User', reverse_delete_rule=CASCADE)
    parking_id = db.ReferenceField('Parking', reverse_delete_rule=CASCADE)
    parkingslot_id = db.ReferenceField(
        'ParkingSlot', reverse_delete_rule=CASCADE)
    start_time = db.DateTimeField(
        verbose_name=u'Start time',
        required=True
    )
    end_time = db.DateTimeField(
        verbose_name=u'End time',
        required=True
    )
    is_cancelled = db.BooleanField(
        verbose_name=u'Is Cancelled',
        default=False
    )

    meta = {}

    def __unicode__(self):
        return self.start_time + ' ' + self.end_time

parkings/forms.py
# -*- coding: utf-8 -*-
from wtforms import *
from wtforms.fields.html5 import DateTimeLocalField
from flask_wtf import FlaskForm
from flask import g
from parkings.models import Booking, ParkingSlot
from datetime import datetime, timedelta


class ParkingBookForm(FlaskForm):
    date = DateField(
        label=u'Select date',
        validators=[validators.DataRequired()],
        default=datetime.utcnow
    )
    start_time = TimeField(
        label=u'Select start time',
        validators=[validators.DataRequired()],
        default=datetime.now() + timedelta(hours=1)
    )
    end_time = TimeField(
        label=u'Select end time',
        validators=[validators.DataRequired()],
        default=datetime.now() + timedelta(hours=2)
    )
    parkingslot_id = HiddenField(
        label=u"Parking slot",
        validators=[validators.DataRequired()])

    def save(self):
        parkingslot_id = self.parkingslot_id.data
        parking_id = ParkingSlot.objects.get(pk=parkingslot_id).parking_id.pk
        date = self.date.data
        start_time = datetime.strptime(
            f'{date} {self.start_time.data}', '%Y-%m-%d %H:%M:%S')
        end_time = datetime.strptime(
            f'{date} {self.end_time.data}', '%Y-%m-%d %H:%M:%S')
        user_id = g.user.pk
        booking = Booking(parking_id=parking_id, parkingslot_id=parkingslot_id,
                          start_time=start_time, end_time=end_time, user_id=user_id)
        booking.save()
        return booking

parkings/views.py
# -*- coding: utf-8 -*-
from flask import (
    Blueprint, render_template, session, g, flash, request, redirect, url_for,
    current_app
)
from accounts.models import User
from parkings.models import Parking, ParkingSlot, Booking
from common.utils import get_signer
from parkings.forms import ParkingBookForm
from feedbacks.models import Feedback
from common.decorators import login_required, is_superuser, is_not_superuser
from datetime import datetime
from bson.objectid import ObjectId


parkings_app = Blueprint('parkings_app', __name__)


@parkings_app.before_app_request
def load_user():
    g.user = None
    if 'user_id' in session:
        try:
            g.user = User.objects.get(pk=session['user_id'])
        except Exception:
            pass


@parkings_app.route('/parkings/search/', methods=['GET', 'POST'])
@is_not_superuser
def search():
    pipeline = [
        {
            '$lookup': {
                'from': 'parkingslot',
                'localField': '_id',
                'foreignField': 'parking_id',
                'as': 'parking_slots'
            }
        }
    ]
    parkings = Parking.objects.aggregate(pipeline)
    return render_template('parking/search.html', parkings=parkings)


@parkings_app.route('/parkings/book/<parking_id>', methods=['GET', 'POST'])
@is_not_superuser
def book(parking_id):
    form = ParkingBookForm()
    if form.validate_on_submit():
        form.save()
        flash(
            u'Successfully booked',
            'success'
        )
        feedback_count = Feedback.objects(user_id=g.user.pk).count()
        if not feedback_count:
            return redirect(url_for('feedbacks_app.feedback'))
        return redirect(url_for('parkings_app.search', parking_id=parking_id))

    pipeline = [
        {
            '$lookup': {
                'from': 'booking',
                'localField': '_id',
                'foreignField': 'parkingslot_id',
                'as': 'bookings'
            }
        }
    ]
    parking = Parking.objects.get(pk=parking_id)
    pipeline = [
        {
            '$match': {
                'parking_id': ObjectId(parking_id)
            }
        },
        {
            '$lookup': {
                'from': 'booking',
                'localField': '_id',
                'foreignField': 'parkingslot_id',
                'as': 'bookings'
            }
        }
    ]
    available_slots = ParkingSlot.objects.aggregate(pipeline)
    return render_template('parking/book.html', form=form, parking_slots=available_slots, parking=parking)


@parkings_app.route('/bookings', methods=['GET', 'POST'])
@login_required
def bookings():
    query = {
        'start_time__gte': datetime.now(),
        'is_cancelled': False
    }
    if not g.user.is_superuser:
        query['user_id'] = g.user.pk
    bookings = Booking.objects.filter(**query)
    return render_template('parking/bookings.html', bookings=bookings)


@parkings_app.route('/bookings/cancel/<booking_id>', methods=['GET'])
@login_required
def cancel(booking_id):
    booking = Booking.objects.get(pk=booking_id)
    if g.user.is_superuser or g.user.pk == booking.user_id:
        bookings = Booking.objects(
            pk=booking_id).update(set__is_cancelled=True)
    return redirect(url_for('parkings_app.bookings'))

templates/parking/book.html
{% extends 'base.html' %}

{% block title %}Book{% endblock %}

{% block content %}

<div class="page-header my-2">
  <h3>{{parking.display_name}}</h3>
  <p>Address: {{parking.address}}</p>
</div>

<form action="" method="post" class="form-horizontal">
  {{ form.hidden_tag() }}
  {% import 'form_macro.html' as form_macro %}
  {{ form_macro.form_field(form.parkingslot_id, with_label=False) }}
  {{ form_macro.form_field(form.date, with_label=True) }}
  {{ form_macro.form_field(form.start_time, with_label=True) }}
  {{ form_macro.form_field(form.end_time, with_label=True) }}
  <div class="form-actions">
    <button id="book_btn" hidden class="btn btn-icon btn-primary">Book</button>
  </div>
</form>

<div>
  <div class="row">
    {% for slot in parking_slots %}
    <div class="col-4 text-center p-2 slot">
      <div class="card" onclick="book('{{slot._id}}')">
        <div class="card-body">
          <h4>{{slot.display_name}}</h4>
          {% if slot.bookings|length > 0 %}
          Bookings
          <ul>

            {% for booking in slot.bookings %}
            <li>
              {{booking.start_time}} ~ {{booking.end_time}}
            </li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

{% block extrahead %}
<style>
  .slot:not(.booked) .card:hover {
    background-color: #007bff;
    color: #fff;
  }

  .slot.booked .card {
    background-color: #fff360;
  }
</style>
{% endblock %}

{% block extrajs %}
<script>
  function book(parkingslot_id) {
    $('#parkingslot_id').val(parkingslot_id);
    $('#book_btn').click();
  }
</script>
{% endblock %}

templates/parking/bookings.html
{% extends 'base.html' %}

{% block title %}Bookings{% endblock %}

{% block content %}

<div class="page-header my-2">
  <h3>Bookings</h3>
</div>

<div>
  {% for booking in bookings %}
  <div class="card mb-2">
    <div class="card-body">
      <h6>
        Parking: {{booking.parking_id.display_name}}
      </h6>
      <h5>
        Slot: {{booking.parkingslot_id.display_name}}
      </h5>
      <p>
        From: {{booking.start_time}}
      </p>
      <p>
        To: {{booking.end_time}}
      </p>
      <a href="{{ url_for('parkings_app.cancel', booking_id=booking.pk) }}" class="btn btn-danger">
        Cancel
      </a>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

templates/parking/search.html
{% extends 'base.html' %}

{% block title %}Search Parking{% endblock %}

{% block content %}

<div class="page-header my-2">
  <h3>Nearby parking lots</h3>
</div>

<div>
  {% for parking in parkings %}
  <div class="card mb-2">
    <div class="card-body">
      <h4>
        <a href="{{ url_for('parkings_app.book', parking_id=parking._id) }}">
          {{parking.display_name}}
        </a>
      </h4>
      <p>
        Address: {{parking.address}}
      </p>
      Total Slots: <span class="badge badge-primary">{{parking.parking_slots|length}}</span>
      <a href="{{ url_for('parkings_app.book', parking_id=parking._id) }}" class="btn btn-primary float-right">
        Book
      </a>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}