accounts/views.py
# -*- coding: utf-8 -*-
from flask import (
    Blueprint, render_template, session, g, flash, request, redirect, url_for,
    current_app
)
from accounts.models import User
from accounts.forms import (LoginForm, SignupForm)
from common.utils import get_signer


accounts_app = Blueprint('accounts_app', __name__)


@accounts_app.before_app_request
def load_user():
    g.user = None
    if 'user_id' in session:
        try:
            g.user = User.objects.get(pk=session['user_id'])
        except:
            pass


@accounts_app.route('/login/', methods=['GET', 'POST'])
def login():
    next = request.values.get('next', '/')
    form = LoginForm()
    form.next.data = next
    if form.validate_on_submit():
        session['user_id'] = str(form.user.pk)
        flash(u'Login successfully', 'success')
        return redirect(next)
    return render_template('accounts/login.html', form=form)


@accounts_app.route('/logout/')
def logout():
    next = request.args.get('next', '/')
    flash(u'Logout successfully', 'success')
    session.pop('user_id', None)
    return redirect(next)


@accounts_app.route('/signup/', methods=['GET', 'POST'])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        form.save()
        flash(
            u'Successfully registered',
            'success'
        )
        return redirect(url_for('accounts_app.login'))
    return render_template('accounts/signup.html', form=form)

feedbacks/views.py
# -*- coding: utf-8 -*-
from flask import (
    Blueprint, render_template, session, g, flash, request, redirect, url_for,
    current_app
)
from common.utils import get_signer
from accounts.models import User
from feedbacks.models import Feedback
from feedbacks.forms import FeedbackForm
from common.decorators import login_required, is_superuser, is_not_superuser

feedbacks_app = Blueprint('feedbacks_app', __name__)


@feedbacks_app.before_app_request
def load_user():
    g.user = None
    if 'user_id' in session:
        try:
            g.user = User.objects.get(pk=session['user_id'])
        except Exception as e:
            pass


@feedbacks_app.route('/feedback', methods=['GET', 'POST'])
@login_required
def feedback():
    form = FeedbackForm()
    if form.validate_on_submit():
        form.save()
        flash(
            u'Thank you for your feedback',
            'success'
        )
        return redirect(url_for('parkings_app.search'))
    feedbacks = Feedback.objects.filter()
    return render_template('feedbacks/feedbacks.html', form=form, feedbacks=feedbacks)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %} - Parking App</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="{% block head_description %}{% endblock %}">
  <meta name="author" content="{% block head_author %}{% endblock %}">

  <!-- Le styles -->
  <link href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <style>
    body {
      padding-top: 60px;
      /* 60px to make the container go all the way to the bottom of the topbar */
    }
  </style>

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="{{ url_for('static', filename='bootstrap/js/html5shiv.js') }}"></script>
  <![endif]-->
  {% block extrahead %}{% endblock %}
</head>

<body>

  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Parking App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
      aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      {% if g.user %}
      <ul class="navbar-nav mr-auto">
        {% if not g.user.is_superuser %}
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('parkings_app.search') }}">Search</a>
        </li>
        {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('feedbacks_app.feedback') }}">Feedback</a>
        </li>
        {% endif %}
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('parkings_app.bookings') }}">Bookings</a>
        </li>
      </ul>
      {% endif %}
      <ul class="navbar-nav ml-auto pull-right">
        {% if g.user %}

        <li class="nav-item active dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            {{ g.user.name }}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" disabled href="#">Bookings</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('accounts_app.logout') }}">Logout</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('accounts_app.login') }}">
            Login
          </a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('accounts_app.signup') }}">
            Signup
          </a>
        </li>

        {% endif %}
      </ul>
    </div>
  </nav>


  <div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    <div id="messages">
      {% for category, message in messages %}
      <div class="alert alert-{{ category }}">
        <a class="close" data-dismiss="alert">&times;</a>
        <strong>{{ message }}</strong>
      </div>
      {% endfor %}
    </div>
    {% endwith %}

    {% block content %}{% endblock %}
  </div> <!-- /container -->

  <!-- Le javascript
    ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="{{ url_for('static', filename='js/jquery-1.10.1.min.js') }}"></script>
  <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
  {% block extrajs %}{% endblock %}
</body>

</html>

templates/form_macro.html
{% macro form_field(field) -%}
    {% set with_label = kwargs.pop('with_label', False) %}
    {% set placeholder = '' %}
    {% if not with_label %}
        {% set placeholder = field.label.text %}
    {% endif %}
    <div class="control-group {% if field.errors %}error{% endif %}">
        {% if with_label %}
            <label for="{{ field.id }}" class="control-label">
                {{ field.label.text }}{% if field.flags.required %} *{% endif %}:
            </label>
        {% endif %}
        <div class="controls">
            {% set class_ = kwargs.pop('class_', '') %}
            {% if field.flags.required %}
                {% set class_ = class_ + ' required' %}
            {% endif %}
            {% if field.type == 'BooleanField' %}
                <label class="checkbox">
                    {{ field(class_=class_, **kwargs) }}
                    {{ field.label.text|safe }}
                </label>
            {% else %}
                {% if field.type in ('TextField', 'TextAreaField', 'PasswordField') %}
                    {% set class_ = class_ + ' input-xlarge' %}
                {% elif field.type == 'FileField' %}
                    {% set class_ = class_ + ' input-file' %}
                {% endif %}
                {{ field(class_=class_, placeholder=placeholder, **kwargs) }}
            {% endif %}
            {% if field.errors %}
                <span class="error help-inline">{{ field.errors|join(', ') }}</span>
            {% endif %}
            {% if field.description %}
                <p class="help-block">{{ field.description|safe }}</p>
            {% endif %}
        </div>
    </div>
{%- endmacro %}

templates/pagination_macro.html
{% macro render_pagination(pagination) %}
  <div class="pagination pagination-large">
    <ul>
  {%- for page in pagination.iter_pages() %}
    {% if page %}
      {% if page != pagination.page %}
        <li><a href="{{ request.base_url }}?page={{ page }}">{{ page }}</a></li>
      {% else %}
        <li class="active"><a href="#">{{ page }}</a></li>
      {% endif %}
    {% else %}
      <li class="disabled"><span class=ellipsis>…</span></li>
    {% endif %}
  {%- endfor %}
    </ul>
  </div>
{% endmacro %}